on:
  pull_request: {}
  push:
    branches:
    - master
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v3
    - run: go test ./...
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v3
    - run: |-
        set -euo pipefail
        RESULT="$(gofmt -s -d -l ./)"
        echo "${RESULT}"
        if [[ $(echo -n "${RESULT}"|wc -l) -gt 0 ]]; then exit 1; fi
